"""empty message

Revision ID: a6a875c42110
Revises: 4f9f4b35043d
Create Date: 2018-12-06 14:58:00.475031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a875c42110'
down_revision = '4f9f4b35043d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('account_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'account_id')
    # ### end Alembic commands ###
