"""empty message

Revision ID: a9d176d445f2
Revises: cdaf07db10cb
Create Date: 2019-07-21 10:27:01.820681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d176d445f2'
down_revision = 'cdaf07db10cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('initial_balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'initial_balance')
    # ### end Alembic commands ###
